### ISSUE TITLE
Provide connection into method.controller.

### ISSUE THREAD

**Issue by glagius** [shirokovnv/phx_json_rpc#48]
Hello.
I'm trying to make some basic auth validation for methods and their parameters, and i can't find a way to add additional information to request.

This is because DefaultPipeline in Router takes metadata from LocalRouter, and not from controller.

This is code from example:
```
def rpc(conn, request) do
    response = Router.handle(request)
    render(conn, "response.json", response)
  end
```
But if I have multiple clients and they only need to perform actions on their own entities, I can't validate their request according to their access level.
I suggest adding a connection as the second parameter, or just a map to forward the necessary tokens.

**Comment by shirokovnv** [comment]
Greetings! 

Glad you tried it out!

As far as I understood, you need to somehow check some user-specific data, like authorization grants and so on, inside the RPC actions, where you don't have access to `conn` structure.

To be honest, I intentionally not passing `conn` into the RPC-router, because it has different "namespace".

Conn is all about "http/https" and rpc doesn't know anything about it.

But I can add something like "user-metadata" parameter (actually just a map, as you said earlier).

Let me know if I understood you correctly and I will implement this in a next release.

**Comment by glagius** [comment]
I think that all we need is to add some kind of middleware for incoming VALIDATED and PARSED request body. 
So, into this middleware we can set any validation logic for connection and incoming parameters.

Also for instance, check how maded Guards in NestJs.

**Comment by shirokovnv** [comment]
Well, in case of checking authorization for **all** incoming requests, I would suggest using [Plug](https://hexdocs.pm/phoenix/plug.html).

And use that plug in a controller, where you do `Router.handle(request)` or in general http router.

If you would like to simply check some of the rpc actions, the temporary solution might be following:
```
plug :authenticate

def rpc(conn, request) do
    response = Router.handle(request)
    render(conn, "response.json", response)
end

defp authenticate(conn, _) do
  # you need to access your rpc requests data here
  # see: https://hexdocs.pm/plug/Plug.Conn.html#module-fetchable-fields
  params = conn.body_params

  # loop through all requests and see, if there are some auth restrictions.
  
  # if request doen't need to be handled, just drop it from body_params map

  # note, that for the end-user it will be not obvious, why request hasn't been handled.

  # just pass conn with mutated body_params
  conn
end
```

**Comment by shirokovnv** [comment]
Check version [0.4.0](https://github.com/shirokovnv/phx_json_rpc/releases/tag/0.4.0)

See this [example](https://hexdocs.pm/phx_json_rpc/PhxJsonRpc.Router.Middleware.html)

For now you can do it in your main rpc router: 

```
middleware([AuthMiddleware])

rpc (...)
```

And in http-controller: 

```
def rpc(conn, request) do
    response = Router.handle(request, conn) # second parameter: meta_data
    render(conn, "response.json", response)
end
```

The `meta_data` parameter accepts any map.

Hope it helps.

**Comment by glagius** [comment]
Thanks alot!
